# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba5a2b9dd8763f9c834264d8c1d22eea3e6ae6aae8d14632d7314e36703ed0a676f6d09d58bc2522409538feb52ef6a400ec0d2d783fea17199af326ffd23ee2

test:
  secret_key_base: e03af6837b79a2e7ba17d9f20b04ed7e972330f3b1427b347709db56d28e39eedf9faa434be0362ff1bf24879b36d437d149dcf5b6239baf835a342b9a3b59bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
